### ISSUE TITLE
Scenario Outlines being Ignored

### ISSUE THREAD

**Issue by odsc-bryan** [mattfritz/protractor-cucumber-framework#17]
Hi,

When attempting to run the step definitions on a cucumber scenario with the following structure:

    Scenario Outline: Example
    Given I have a table
    When the table has been populated
    Then the <Type> has Built <B>
    Then the <Type> has Sold <S>
    Then the <Type> has Destroyed <D>
    
    | Type | B | S| D |
    | Car | 456 | 357 | 666 |
    | Boat | 456 | 357 | 666 |
    | Train |  456 | 357 | 666 |
    | Plane |  456 | 357 | 666 |

The scenario is completely ignored by protractor. I was wondering if Scenario Outlines were supported by this framework, and if not, is there plans for them to be supported?

Thanks!

**Comment by darrinholst** [comment]
this framework is just a pass through to cucumberjs which supports scenario outlines - https://github.com/cucumber/cucumber-js/blob/master/features/scenario_outlines.feature

I think you're missing the `Examples:` line.

**Comment by odsc-bryan** [comment]
You're absolutely right! Thank you for the help!
