### ISSUE TITLE
How to debug with browser (run with karma or something like that)?

### ISSUE THREAD

**Issue by Sophia-nguyen** [mattfritz/protractor-cucumber-framework#21]

**Comment by leegee** [comment]
Why would something special need to be done? What is lacking in the 'usual' Protractor way[1]?

[1] https://github.com/angular/protractor/blob/master/docs/debugging.md

**Comment by mattfritz** [comment]
@Sophia-nguyen Can you please clarify? You should be able to pass `debug: true` to start Protractor in debug mode, and then use `browser.pause()` or `browser.debugger()` in your Karma tests at the point you want to inspect.

I'm closing this for now, let me know if you still have issues with the plugin and I'll gladly reopen it.
