### ISSUE TITLE
`npm test` fails

### ISSUE THREAD

**Issue by leegee** [mattfritz/protractor-cucumber-framework#22]
Followed all the instructions in the README.

Please find output of `npm test` attached.
[testout.txt](https://github.com/mattfritz/protractor-cucumber-framework/files/142975/testout.txt)

**Comment by darrinholst** [comment]
Are you seeing `Starting HTTPster v1.0.3 on port "8081" from testapp/` from the `npm start` command?

**Comment by leegee** [comment]
Not exactly:

    > protractor-cucumber-framework@0.3.4 start D:\src\protractor-cucumber-framework
    > httpster -d testapp/ -p `node -p 'process.env.HTTP_PORT || require("./spec/environment").webServerDefaultPort'`

    Starting HTTPster v1.0.3 on port "'process.env.HTTP_PORT" from testapp/

**Comment by leegee** [comment]
I've just set up a little test your lib with my code base, and I've got to say -- well done, what lovely work! Thank you so much for saving the hassle of going through integrating these libraries for my client. I owe you a beer.

**Comment by mattfritz** [comment]
@leegee Are you still having issues with this? I can't replicate the issue but I also don't have a Windows machine to test on. Let me know and I'll reopen this ticket. Cheers!

**Comment by leegee** [comment]
I haven't run the command since — if you would like me to, please let me 
know.

**Comment by pratmehta** [comment]
@mattfritz  :-1: 
 i m facing the issue 
> httpster -d testapp/ -p `node -p 'process.env.HTTP_PORT || require("./spec/environment").webServerDefaultPort'`

Starting HTTPster v1.0.3 on port "'process.env.HTTP_PORT" from testapp/

App is not opening 

do i need to install someting , i followed the step mentioned by you

**Comment by tspiderx** [comment]
I am also seeing only:
Starting HTTPster v1.0.3 on port "'process.env.HTTP_PORT" from testapp/

Note there is a ' before the process.env.HTTP_PORT text.

Could it be that i am missing some configuration? The instruction seems straight forward enough and I can't find any hint for this.

Thanks if anyone can help!
