### ISSUE TITLE
Support for cucumber 0.10.x

### ISSUE THREAD

**Issue by Sabartius** [mattfritz/protractor-cucumber-framework#24]
Hi,

i cannot update the cucumber dependendy of my project to 0.10.x, because the protractor-cucumber-framework peer-dependency is set to 0.9.x.

Hope this will be adressed soon.

**Comment by mattfritz** [comment]
Updated `peerDependencies` so Cucumber can be upgraded up to, but not including, `v1.x`. Released in `v0.5.0`. Thanks!
