### ISSUE TITLE
Issue: Running multiple scenarios in 1 feature file (Application with SSO)

### ISSUE THREAD

**Issue by sriniprasad** [mattfritz/protractor-cucumber-framework#26]
We are using the "protractor-cucumber-framework" for our test automation needs, we encountered an issue while running multiple scenarios in 1 feature file.

**Description**: The application under test is having a SSO login, when i run the scenarios using the feature tag / scenario tag, the window for the second scenario opens before the first scenario closes. We tried to close the Webdriver window using browser.close();, in that case the second scenario fails due to the reason "Unable to find session id"

Feature File:
@bookSearch
Feature: To search a book on the online store
  As a user I want to search a book online so that I can select a book online

  @authorName
  Scenario: Search with Book Name
    Given I am on the online search page to look up for a book based on author Name
    When I click on search
    Then the search results related to the book name should be displayed

  @Title
    Scenario: Search with Title
    Given I am on the online search page to look up for a book based on Title
    When I click on the serach after entering the Title
    Then the search results related to the book  Title should be displayed

Config file:

exports.config = {

		framework: 'custom',

		  frameworkPath: require.resolve('protractor-cucumber-framework'),
    suites: {

        DemoSearch: 'test/features/BookSearch/bookSearch.feature'
    },

    cucumberOpts: {

      require:'test/TestScripts/BookSearch/*_Search.js',
    
     //   tags:'@authorName,@Title',

        format: 'summary',
        keepAlive: false
    },

     capabilities: {
        browserName: 'internet explorer',
         version:'8',
        browserAttachTimeout:20000,
        enableElementCacheCleanup:true,
        javascriptEnabled:true,
       	ignoreProtectedModeSettings:true,
        'ie.ensureCleanSession':false,
         shardTestFiles:true,
         maxInstances:2
         
    },

    resultJsonOutputFile: 'TestResult/report.json',

    jasmineNodeOpts: {
        defaultTimeoutInterval: 20000
    }

};

The step definitions are in 2 different .js files, we tried with all step definitions in 1 file, that doesn't work too. Let us know if there any solution that can be implemented or the Framework / tool needs a update? 

Any help is highly appreciated!

**Comment by sriniprasad** [comment]
It was more of a "StaleelementReference" issue, we handled it after implementing ptor wait and sync code. Closing the issue

**Comment by nachchid** [comment]
I am still seeing this issueon version 0.6.0. Is this fixed ?
