### ISSUE TITLE
CreateProcess error=193, %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by rdonthi** [mattfritz/protractor-cucumber-framework#28]
Hi 
I am experiencing the following error when run the test.. not sure where it went wrong  please guide if anyone has experienced this issue before.

Error running lib.feature: 
Cannot run program "C:\Users\ranjith.donthi\protractor-cucumber-framework\node_modules\cucumber\bin\cucumber.js" (in directory "C:\Users\ranjith.donthi\protractor-cucumber-framework\spec"): CreateProcess error=193, %1 is not a valid Win32 application

**Comment by stevehipwell** [comment]
Use `cucumber-js` not `cucumber.js` on windows.

**Comment by mattfritz** [comment]
Thanks for the report! @stevehipwell suggestion to use the `cmd` executable should work on a Windows machine. I'm going to close this for now, but let me know if you have further information and I'll reopen
