### ISSUE TITLE
Before hooks are not working as expected

### ISSUE THREAD

**Issue by NaveenKVN** [mattfritz/protractor-cucumber-framework#29]
I am using cucumber 0.10.2, "gulp-protractor-cucumber-html-report": "0.0.9"
And i have 
module.exports = function beforeHooks() {
this.Before('@splan', function () {
        var world = this;
        splan.maximizeBrowser();
        // Load the homepage.
        splan.get();
        // Clear localStorage.
        world.clearLocalStorage();

        // Reload the page with empty localStorage.
        splan.get();
        //console.log("Before service Planning");
        browser.wait(function () {
            return browser.executeScript('return !!window.angular');
        }, 5000); // 5000 is the timeout in millis

        //done();
    });

    this.Before('@cped', function () {
        //code/...
var world = this;
        cped.maximizeBrowser();
        // Load the homepage.
        cped.get();
        // Clear localStorage.
        world.clearLocalStorage();

        // Reload the page with empty localStorage.
        cped.get();
        //console.log("Before service Planning");
        browser.wait(function () {
            return browser.executeScript('return !!window.angular');
        }, 5000); // 5000 is the timeout in millis

        //done();
        
    });
};

While I am executing @splan test cases, it is executing both @splan and @cped hooks.
And when I downgraded the cucumber to 0.9.2 version it worked well..

And when  I am using the callback done the browser is hanging on url :data:text/html,<html></html>,If I am removing callback done, then its working fine.

**Comment by szikszail** [comment]
Hi,

In CucumberJS the hook definition changed a bit: https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#0100-2016-04-01

**Comment by mattfritz** [comment]
Correct, syntax should be something like:

```js
this.Before({tags: ['@splan']}, function () {
  // hook stuff
}
```

Closing, please post more info if fixing the syntax does not help.

**Comment by NaveenKVN** [comment]
Thankyou
