### ISSUE TITLE
require globs are not expanded

### ISSUE THREAD

**Issue by darrinholst** [mattfritz/protractor-cucumber-framework#3]
Looks like glob expansion that protractor [did for us](https://github.com/angular/protractor/blob/2.5.1/lib/frameworks/cucumber.js#L25) is missing for the require option. I did it manually in my conf file, but it would be nice if this could be brought back.

before:
```js
    cucumberOpts: {
      format: ['json:build/test-results/protractor.json', 'pretty'],
      require: ['features/step_definitions/**/*.js', 'features/support/**/*.js']
    },
```

after:
```js
    cucumberOpts: {
      format: ['json:build/test-results/protractor.json', 'pretty'],
      require: glob.sync('features/step_definitions/**/*.js').concat(glob.sync('features/support/**/*.js'))
    },
```

**Comment by LoicMahieu** [comment]
Yep. Due to #1 I will look at ASAP

**Comment by mattfritz** [comment]
Fixed in https://github.com/mattfritz/protractor-cucumber-framework/commit/23bd1ba53b671215aa04e8abc7a81fb7c07a24ec 

Thanks for the heads up @darrinholst
