### ISSUE TITLE
browser.manage().DeleteAllCookies() Not Deleting Cookies in Firefox 

### ISSUE THREAD

**Issue by stevenmccord** [mattfritz/protractor-cucumber-framework#30]
I have submitted something into the protractor team, but something I was thinking was maybe it could be a cucumber issue as well.  Does this support deleting cookies from protractor?  I couldn't find anything in the forums.  Thanks!

**Comment by darrinholst** [comment]
My guess would be that it would be a selenium issue if anything. https://github.com/SeleniumHQ/selenium/issues. This library would not have any effect on it.
