### ISSUE TITLE
protractor-cucumber HTML reporting feature request

### ISSUE THREAD

**Issue by igniteram** [mattfritz/protractor-cucumber-framework#31]
I have been using the "resultJsonOutputFile" feature of protractor which generates an Json file which has to be converted to xml format which could be then displayed as HTML report. can we have protractor-cucumber to generate html reports or support at least cucumber-html-report plugin in cucumberOptions?? are there any PR's raised for this?
Note: I am aware that there is a work around by installing node-module called cucumber-html report which uses mustache to convert json files to html reports.

**Comment by darrinholst** [comment]
This library is just glue code between cucumber and protractor. Any options or formatters that cucumber supports can be passed through to it in the cucumberOpts. If there is something you feel is missing in cucumber itself it's probably better to raise that issue over there. Looks like there there is [one](https://github.com/cucumber/cucumber-js/issues/94) open there now.

**Comment by mattfritz** [comment]
Closing in favor of aforementioned https://github.com/cucumber/cucumber-js/issues/94
