### ISSUE TITLE
Why feature steps and scenarios are shown passed even though the tests have failed?

### ISSUE THREAD

**Issue by igniteram** [mattfritz/protractor-cucumber-framework#32]
This is actually quit annoying, when I run the tests and scenarios , in command line/terminal the scenarios and steps are shown passed but actually the tests have failed. I am aware that protractor and cucumberJS run methods asynchronously but this is quit misleading.

<img width="634" alt="screen shot 2016-05-29 at 12 12 43 am" src="https://cloud.githubusercontent.com/assets/15998104/15629271/59a684aa-2532-11e6-9323-074c357e2ade.png">
<img width="752" alt="screen shot 2016-05-29 at 12 21 26 am" src="https://cloud.githubusercontent.com/assets/15998104/15629302/5540566a-2533-11e6-9baa-d9040c5c613b.png">
<img width="752" alt="screen shot 2016-05-29 at 12 24 13 am" src="https://cloud.githubusercontent.com/assets/15998104/15629317/bf7657aa-2533-11e6-9c0a-3ceff36ea622.png">

**Comment by darrinholst** [comment]
You need to either use the "done" callback in your step definitions or
return a promise. Otherwise cucumber doesn't know when your asynchronous
actions are complete. I always make it a habit to return a promise on every
step.

**Comment by igniteram** [comment]
@darrinholst But as far as I know cucumberJS supports synchronous step definitions, this should not happen ideally, plz correct me if i am wrong.

**Comment by darrinholst** [comment]
Sure, that's what happens if you don't use the callback or return a promise, but since nearly everything you do in protractor is asynchronous that's not going to help you much.

**Comment by igniteram** [comment]
yep that makes sense, i have started returning promises and the steps are running as expected.
Thanks for clarifying! @darrinholst 😄
