### ISSUE TITLE
Exclude particular step definition from CucumberOpts

### ISSUE THREAD

**Issue by igniteram** [mattfritz/protractor-cucumber-framework#34]
currently i have setup my tests with protractor and cucumber and i have the following cucumberOpts -
```
cucumberOpts: {

        monochrome: true
        , strict: true
        , plugin: ["pretty"]
        , require: ['../StepDefinitions/*.js', '../Support/*.js']
        , tags: '@AllureScenario,@Regression,@ProtractorScenario,~@DatabaseTest' 
    }
```
I have to exclude a particular step definition from require key, is there a way for it, i have searched various forums - SO, gitter but no help, if its a new feature request please consider it.

**Comment by darrinholst** [comment]
Try a `!` glob pattern. https://www.npmjs.com/package/glob

**Comment by mattfritz** [comment]
Thanks for the report! @darrinholst suggestion should work to exclude the file. Let me know if you have additional information and I'll reopen this issue

**Comment by djom20** [comment]
Hi,

I was working with this format two days ago:

```
cucumberOpts: {
  exclude: ['file.js', 'file2.js'],
  require: ['step_definitions/**/*_steps.js'],
  format: 'pretty',
  tags: ['@complete','~@todo'],
  keepAlive: false
}
```

But right now it's not working I don't know why. Recently I update all my package.json maybe the last protractor version has an issue. Also I use the tags to exclude the steps that I wont to run.

**Comment by darrinholst** [comment]
@djom20 I'd suggest not updating everything in package.json all at once. Instead selectively update one at a time and see if the tests still work after each. My guess is that you updated a major version of cucumber. There are breaking changes in each major version update that you'll have to address.

**Comment by djom20** [comment]
That's right @darrinholst so I share my package.json to in case someone knows something or helps to someone.

```
"dependencies": {
    "async": "^1.5.2",
    "chai": "^3.5.0",
    "chai-as-promised": "^5.3.0",
    "chance": "^1.0.6",
    "colors": "^1.1.2",
    "cucumber": "^1.0.0",
    "cucumber-html-reporter": "latest",
    "cucumberjs-allure-reporter": "latest",
    "find": "^0.2.7",
    "glob": "^7.1.2",
    "karma": "^2.0.2",
    "karma-chai": "^0.1.0",
    "karma-chai-as-promised": "^0.1.2",
    "karma-sinon": "^1.0.4",
    "karma-sinon-chai": "^1.2.0",
    "lodash": "^4.17.10",
    "moment": "^2.15.0",
    "protractor": "^5.3.2",
    "protractor-cucumber-framework": "^0.6.0",
    "protractor-html-screenshot-reporter": "latest",
    "request": "^2.87.0",
    "selenium-standalone": "^6.15.0",
    "sinon-chai": "^3.1.0",
    "underscore": "^1.8.3"
  },
  "devDependencies": {
    "allure-commandline": "^1.4.23",
    "gherkin-lint": "^2.11.1",
    "log-timestamp": "^0.1.2",
    "mocha": "^5.2.0",
    "node-notifier": "^4.6.1"
  }
```
