### ISSUE TITLE
Can't Use Protractor API?

### ISSUE THREAD

**Issue by JimTheMan** [mattfritz/protractor-cucumber-framework#35]
Hi, I'm VERY confused about the proper way to use this.

I thought that the whole point of using cucumber with protractor was that you can use the protractor api in the step definition methods. However, when I put things like element(by.css(.something)) it gives me errors, "element is not a function". 

All of the Protractor methods cause the test runner to crash. How can I use the Protractor api in the step definition methods? Thanks.

**Comment by darrinholst** [comment]
Did you install protractor itself? This package doesn't depend on it directly. I have a very simple example project [here](https://github.com/darrinholst/protractor-cucumber-example) that may help you.

**Comment by JimTheMan** [comment]
Hi! Thanks for sharing that. :) 
My problems are all within the step definition file. I started with gulp-angular generator, and those protractor tests "just worked" with my first js.conf, but I see now that it's actually using Jasmine with protractor to do assertions. 

That's my problem. I want to do assertions against like protractor element.getText() or element.isPresent(). 

I think Jasmine can't run with require so you need to use chai (someone please correct me. I don't like chai. lol). I see you are bringing in chai in your steps.js file, but you agent really doing any assertions. The "expect" and "to.be" are from chai, but where are you getting "element" from? However,  I'm getting weird results because I think protractor uses promises alot, but it might work with "chai as promised".

Thanks.

**Comment by darrinholst** [comment]
That sample was just to show the glue between cucumber and protractor working. I'm not doing any assertions on an angular app there, but there are assertions like [here](https://github.com/darrinholst/protractor-cucumber-example/blob/master/features/step_definitions/steps.js#L19).

I use chai-as-promised in the real world and it ends up looking something like...
``` javascript
return expect(element(by.css('.something')).getText()).to.eventually.eql('anything');
```

`element` is provided by protractor itself on the global object

**Comment by mattfritz** [comment]
This issue looks to be resolved, so I'm going to close it.

@JimTheMan let me know if that is not the case and you have an issue with the repo
@darrinholst thank you for your help as always!
