### ISSUE TITLE
Adding Jasmine?

### ISSUE THREAD

**Issue by JimTheMan** [mattfritz/protractor-cucumber-framework#36]
Hi, 

Normally Protractor works with jasmine, but I think changing the framework to this:

```
  framework: 'custom',
  frameworkPath: require.resolve('protractor-cucumber-framework'),
```

in protractor.conf.js removes Jasmine as I'm getting "expect is not a function" errors. Is it possible for me to add Jasmine to this setup and do assertions right in a step definition file without making any describes full of it's?

**Comment by eymemathew** [comment]
I'm interested in the same feature. @mattfritz is this something you are considering, as our entire team would love to use this module if we have Jasmine support.

**Comment by JimTheMan** [comment]
It's true. Most projects' (at least the ones I've been workin on recently) have regular unit tests and even the regular e2e protractor tests integrated with Jasmine. It's quite annoying to have to switch over to chai assertions for cucumber protractor tests.

**Comment by mattfritz** [comment]
This is not something this package is capable of doing... 

`protractor-cucumber-framework` is just glue to hook up the Cucumber runner with Protractor, which is why you have to include your own assertion library. Jasmine is a batteries-included runner with an assertion library, so the two are mutually exclusive. 

Let me know if you have any questions or additional info and I'll reopen this ticket.

**Comment by JimTheMan** [comment]
Thanks for shedding some light on this,  @mattfritz. Perhaps what we need is a separate project that is purely an assertion library but with exactly the syntax that Jasmine uses.

**Comment by darrinholst** [comment]
How far off is chai's expect syntax off from jasmines? I thought they were pretty similar.

**Comment by JimTheMan** [comment]
Chai: ew. why the unnecessary chaining functions?
`expect(name).to.equal('Jim');`

Jasmine: ah, so relaxing and intuitive, a matcher function that does what it says.
`expect(name).toEqual('Jim');`

**Comment by eymemathew** [comment]
Thanks for the response Matt! 
There was a module that worked with Jasmine and Cucumber, but the syntax of the feature file is different and the module is now deprecated: https://github.com/DealerDotCom/protractor-jasmine-cucumber. Just sharing it to see if anyone has any thoughts.

**Comment by eymemathew** [comment]
Hi @mattfritz Just wanted to check if the module mentioned in the comment above: https://github.com/DealerDotCom/protractor-jasmine-cucumber helps with any ideas to integrate jasmine with Cucumber

**Comment by ebacka** [comment]
What assertor can be used in this case to test dom? It seems that chai-dom has issues https://github.com/nathanboktae/chai-dom/issues/33
