### ISSUE TITLE
Report is not generated properly when SharedTestFiles:true

### ISSUE THREAD

**Issue by NaveenKVN** [mattfritz/protractor-cucumber-framework#37]
framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    rootElement: 'body', // location of ng-app directive
    //seleniumAddress: 'http://localhost:4444/wd/hub',
    capabilities: {
        browserName: 'chrome',
        shardTestFiles: true,
        maxInstances: 10,
        cucumberOpts: {
            format: 'json:./cukes-pro/reports/cucumber.chrome.json'
        }
    }

When I am doing the shared execution=true for parallel , then the report is not having the complete execution result.

**Comment by mattfritz** [comment]
Thank you for the report. I'm investigating a solution proposed here in issue https://github.com/mattfritz/protractor-cucumber-framework/issues/46 . Moving all discussion there.

**Comment by NaveenKVN** [comment]
Thankyou
