### ISSUE TITLE
Getting error in Windows

### ISSUE THREAD

**Issue by rjrajasekaran** [mattfritz/protractor-cucumber-framework#39]
While running 'npm test', I am getting error.

running: node_modules/protractor/bin/protractor spec/cucumberConf.js
>>> fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
running: node_modules/protractor/bin/protractor spec/cucumberConf.js --cucumberO
pts.tags @failing
>>> fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
running: node_modules/protractor/bin/protractor spec/cucumberConf.js --cucumberO
pts.tags @failing --cucumberOpts.fail-fast
>>> fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
running: node_modules/protractor/bin/protractor spec/cucumberConf.js --cucumberO
pts.tags @strict --cucumberOpts.strict
>>> fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
running: node_modules/protractor/bin/protractor spec/cucumberConf.js --cucumberO
pts.tags @strict
>>> fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
running: node_modules/protractor/bin/protractor spec/multiConf.js --cucumberOpts
.tags @failing
>>> fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
Summary: fail
npm ERR! Test failed.  See above for more details.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

**Comment by mattfritz** [comment]
Thank you for the report! I just started grooming issues and added some comments to a duplicate. Please see here for additional info: https://github.com/mattfritz/protractor-cucumber-framework/issues/45
