### ISSUE TITLE
protractor + cucumber not working on angular 2

### ISSUE THREAD

**Issue by kamran-pervaiz** [mattfritz/protractor-cucumber-framework#42]
Hi guys,

I created this issue on cucumberjs but didn't get much help. could anyone of you figure it out?

https://github.com/cucumber/cucumber-js/issues/612

**Comment by JimTheMan** [comment]
Looks like you figured it out, right? Does it work now? :)

**Comment by mattfritz** [comment]
Is this resolved? I'm going to close it for now, but let me know if you have more issues.

**Comment by kamran-pervaiz** [comment]
@mattfritz yes thanks, it was resolved.
