### ISSUE TITLE
Question (More So Than Issue)

### ISSUE THREAD

**Issue by bhreinb** [mattfritz/protractor-cucumber-framework#50]
Hi There,

Apologies for creating an issue but am not sure where is the best place to post this question. Perhaps here is not the best place but anyway I hope somebody can help with this.

I have downloaded your project "project-cucumber-framework" and ran as per instructions. It runs as expected which is great. Now I take a copy of the "package.json" file and move it to another project called "ProtractorSample" for example. The contents are listed below

{
  "name": "Test123",
  "version": "1.0.0",
  "description": "Test,
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Bhreinb",
  "license": "MIT",
  "dependencies": {
    "debug": "^2.2.0",
    "glob": "^7.0.3",
    "object-assign": "^4.0.1",
    "q": "^1.4.1"
  },
  "peerDependencies": {
    "cucumber": ">= 0.9.1"
  },
  "devDependencies": {
    "chai": "^3.4.1",
    "chai-as-promised": "^5.2.0",
    "cucumber": "^1.0.0",
    "httpster": "^1.0.1",
    "protractor": "^3.2.0",
    "protractor-cucumber-framework": "^0.6.0"
  }
}

and I run with the following config file.

exports.config =
{
    
	framework: 'custom',
	
	// path relative to the current config file
	frameworkPath: require.resolve('protractor-cucumber-framework'),
	
	DirectConnect: true,
	
	allScriptsTimeout: 20000,

	// Capabilities to be passed to the webdriver instance.
	capabilities: {
    
		browserName: 'chrome',
		
		pageLoadingStrategy: 'eager',
		
		ignoreProtectedModeSettings: true
				
	},
	
	// Spec patterns are relative to the location of the spec file. They may include glob patterns.
	suites: {

		testpage: 'features/browse.feature'
		
		//search: ['tests/e2e/contact_search/**/*Spec.js', 'tests/e2e/venue_search/**/*Spec.js']
		
	},
	
	resultJsonOutputFile: 'testoutput.json',
    
	cucumberOpts:
	{
		
		require: 'features/step_definitions/*_steps.js',
		
        format: "pretty",
        
        profile: false,
        
        'no-source': true
    
	},
	
	onPrepare: function() 
	{
		
		browser.manage().deleteAllCookies();
		
		//window.sessionStorage.clear();
		
		//window.localStorage.clear();
		
        browser.driver.manage().window().maximize();
        
        browser.ignoreSynchronization = false;
    
	}

};

The test passes but for the life of me I can't figure why the test execution is different in that I get the following output

[21:56:56] I/local - Starting selenium standalone server...
[21:56:56] I/launcher - Running 1 instances of WebDriver
[21:56:56] I/local - Selenium standalone server started at http://192.168.0.22:33051/wd/hub
Feature: Visiting Angular's website

    As a user
    I should be able to enter my name in the textbox and the message should contain my name

cucumber event handlers attached via registerHandler are now passed the associated object instead of an event
getPayloadItem will be removed in the next major release
  Scenario: User tries out search bar
    [32mGiven I go to angular's website and I enter hello into the name box[39m
    [32mThen the greeting should be Hello hello![39m

  Scenario: User tries out search bar
    [32mGiven I go to angular's website and I enter bye into the name box[39m
    [32mThen the greeting should be Hello bye![39m

2 scenarios ([32m2 passed[39m)
4 steps ([32m4 passed[39m)
0m00.006s
[21:57:14] I/local - Shutting down selenium standalone server.
[21:57:14] I/launcher - 0 instance(s) of WebDriver still running
[21:57:14] I/launcher - chrome #01 passed

in that the test execution time is way off (4th last line). It should be 8 seconds or so. Any ideas what I'm doing wrong? Many thanks in advance as to any help regarding the above.

Btw the duration number wrote to the JSON file what is that measured in? I initially thought it to be unix time but it would appear not to be. Sorry for all the questions I'm a newbie per say.

**Comment by bhreinb** [comment]
Hi Antda,

Many thanks for your response. I think your assertions are correct. I was using the following at the end of a step function

this.When(/^Employer Code (.+) Is Entered And User Logs On$/, function (EmployerCode, next)
	{
		
		//1. Enter <EmployerCode>
		element(by.id('employee-code')).sendKeys(EmployerCode);
		
		//2. Press Login In Button
		element(by.buttonText('Login')).click();
		
		next();
		
	});

however when I add the following to a step definition 

this.Then(/^The Browser Title Should Equal (.+) And The Popup Frame Should Display (.+)$/, {timeout: 30 * 1000}, function (BrowserTitle, PopupFrameGreeting, next)
	{
		
		//1. Expect Browser Title To Equal Passed In Value
		expect(browser.getTitle()).to.eventually.equal(BrowserTitle);
		
		this.RunNonAngular(function()
		{
			
			var iFrame = element(by.id('fbContent'));
			
			expect(iFrame.waitReady()).to.be.truthy;
			
			//Need to switch this way because of issue https://github.com/angular/protractor/issues/1846
			browser.switchTo().frame(iFrame.getWebElement());
			
			var Label = element(by.id('lblRequestActionText'));
			
			expect(Label.waitReady()).to.be.truthy;
			
			//2. Pop up Frame To Equal Passed In Value
			expect(Label.getText()).to.eventually.equal(PopupFrameGreeting).and.notify(next);
		      
		})
		
	});

namely, "and.notify(next)" I do get more accurate test run times. Thanks for your help.

**Comment by antda** [comment]
Nice to hear. No problem.
