### ISSUE TITLE
Project status & revival?

### ISSUE THREAD

**Issue by AlexandrosD** [mattfritz/protractor-cucumber-framework#69]
It seems that the project is stale a long time now, and @mattfritz has not provided any feedback, unfortunately.
Perhaps we should do some coordinated actions to fork and & revive the project, since it is left behind.

I'd like to see your thoughts on this, and your willingness to contribute.

**Comment by darrinholst** [comment]
I'd hate to see a fork, but I understand when something like this falls off your day to day priorities. I wonder what it would take to get this back under the angular org? There are a [few](https://github.com/angular?utf8=%E2%9C%93&q=protractor&type=&language=) protractor related repos there. Otherwise, if we could get a couple core committers added to handle the PRs that would be helpful.

**Comment by jan-molak** [comment]
I've been working in the protractor/cucumber integration area quite a lot recently as part of [Serenity/JS](http://serenity-js.org) and have quite a few features in mind for this project too if there's anyone happy to handle the PRs?

If not, I'll continue adding them as part of [Serenity/JS](http://serenity-js.org) and maybe backport here if/when there's any interest?

**Comment by mattbrunetti** [comment]
FWIW I've been using this package just a few days and I absolutely love what it ties together and brings to the table. I'm thinking about this issue and will surely make another comment.

**Comment by mattbrunetti** [comment]
@AlexandrosD What exactly about this project is stale? It seems to be doing alright to me...

**Comment by mattbrunetti** [comment]
Merge conflicts when we try to merge some particular combination of the open PR branches to get our needed features?

**Comment by AlexandrosD** [comment]
It tends to be outdated. Look how many PRs are still there open. I didn't
say it doesn't work..

On Jan 21, 2017 04:09, "Matthew Francis Brunetti" <notifications@github.com>
wrote:

Merge conflicts when we try to merge some particular combination of the
open PR branches to get our needed features?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mattfritz/protractor-cucumber-framework/issues/69#issuecomment-274225197>,
or mute the thread

**Comment by AlexandrosD** [comment]
Dear @mattfritz - we definitely need your thoughts and feedback on this.

**Comment by darrinholst** [comment]
@sjelin is there any interest in or do we have any options for pulling this back under the angular org? Our leader has gone silent here?

**Comment by jan-molak** [comment]
Hey guys just a quick update on my efforts on the protractor/cucumber integration front.

The project I am helping with couldn't wait for several of the tickets here to be resolved, especially around running sharded tests and supporting the latest version of Protractor (#25, #38, #40, #46, #55, #59, #60, #61, #62, #63, #67).

As we didn't want to maintain a fork that might never get merged, I've decided to add Cucumber support to [Serenity/JS](http://serenity-js.org), which can now act as a drop-in replacement of the `protractor-cucumber-framework` (with most of the above issues addressed and others to be addressed shortly - contributions welcome! :-) ).

The [Serenity/JS implementation](https://github.com/jan-molak/serenity-js/tree/master/src/serenity-cucumber) is not a fork of this repository, but a complete re-write.

To use it, install the library:
```
npm install serenity-js --save-dev
```

and add the following line to your Protractor config (as per the [tutorial](http://serenity-js.org/from-scripts-to-serenity/readme.html)):

```
exports.config = {
  framework: 'custom',
  frameworkPath: require.resolve('serenity-js'),
}
```

Additionally, Serenity/JS implementation supports both [Cucumber](http://serenity-js.org/cucumber/readme.html) and [Mocha](http://serenity-js.org/mocha/readme.html) test frameworks and can produce [Serenity BDD-compatible HTML reports](http://serenity-js.org/overview/reporting.html) together with screenshots, etc.

Thoughts and contributions welcome!

Best,
Jan

**Comment by nicojs** [comment]
Dear @mattfritz,

We had such great times together. Please come back to us. Don't ever leave us. We need you! 

Sincerely,
nicojs

**Comment by csvan** [comment]
Agreed here. @mattfritz I hope you are a well, and it is certainly nobody's business why you are not maintaining this as actively anymore. However, please, please pass on the reins to somebody else if you do not intend to return to it.

**Comment by mattbrunetti** [comment]
@mattfritz I nominate @darrinholst for new owner. Though, I have no idea if he wants that responsibility.

**Comment by mattbrunetti** [comment]
For anyone following this issue, @darrinholst has published his fork on npm as [@darrinholst/protractor-cucumber-framework](https://www.npmjs.com/package/%40darrinholst%2Fprotractor-cucumber-framework)

I think it would be beneficial for the community for his fork to be on npm as [protractor-cucumber-framework](https://www.npmjs.com/package/protractor-cucumber-framework). We could follow [npm's dispute resolution policy for package names](https://www.npmjs.com/policies/disputes) to accomplish that.

**Comment by 77ganesh** [comment]
Hi! I see that most of the issues i'm facing already are resolved, but not published to npm. Any updates on this?

**Comment by mattfritz** [comment]
Sorry for the delay, please see https://github.com/mattfritz/protractor-cucumber-framework/issues/73

**Comment by AlexandrosD** [comment]
Closing this one - Let the discussion continue on https://github.com/mattfritz/protractor-cucumber-framework/issues/73
