### ISSUE TITLE
Assertions [launcher] Process exited with error code 1

### ISSUE THREAD

**Issue by asafamit** [mattfritz/protractor-cucumber-framework#8]
When I run tests assertion errors exit with code 1 rather than continue with step executions

AssertionError: expected 'X' to include 'Y'
[launcher] Process exited with error code 1

I'm also not getting any console report colours compared to execution directly via cucumberjs

My setup if fairly simple:

protractor.conf.js 
```
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  directConnect: true,
  specs: ['test/features/*.feature'],
  // set to "custom" instead of cucumber.
  framework: 'custom',

  // path relative to the current config file
  frameworkPath: './node_modules/protractor-cucumber-framework',

  // relevant cucumber command line options
  cucumberOpts: {
    require: 'test/features/*.js',
    format: "pretty"
  },
  onPrepare: function() {
    browser.ignoreSynchronization = true;
    browser.baseUrl = "http://localhost:3000";
  }
};
```
stepDefinitions
```
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);

var expect = chai.expect;

module.exports = function() {
    this.When(/^I sign in as "([^"]*)"$/, function (arg1, next) {
      browser.get("/");
      // Assertion error here will exit the process
      expect(browser.getTitle()).to.eventually.contain("X");
      element(by.css('[type="email"]')).sendKeys('a@a.com');
      element(by.css('[type="password"]')).sendKeys('password');
      element(by.css('[type="submit"]')).click();
      next();
    });
}
```
Thanks

**Comment by mattfritz** [comment]
The color issue should be fixed by https://github.com/mattfritz/protractor-cucumber-framework/pull/7 `v0.3.0`

How many features do you have in your suite? If you have only one, the `I sign in as ...` step will fail which should fail the feature as well and stop execution. If you have more features, it should move on to those after this feature fails. Let me know and I'll take a look.

**Comment by asafamit** [comment]
Thanks for fixing the color.

The other features are not being executed but it just dumps all of them as passed.  I simplified my test, here are the results (all the scenarios should fail as the title is not X,Y or Z)

feature 1
```
Feature: XY
  Scenario: I want X
    When I want X
  Scenario: I want Y
    When I want Y
```

feature 2
```
Feature: Z
  Scenario: I want Z
    When I want Z
```
step definition:
```
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);

var expect = chai.expect;

module.exports = function() {

    this.When(/^I want X$/, function (next) {
      browser.get("/");
      expect(browser.getTitle()).to.eventually.contain("X");
      next();
    });

    this.When(/^I want Y$/, function (next) {
      browser.get("/");
      expect(browser.getTitle()).to.eventually.contain("Y");
      next();
    });

    this.When(/^I want Z$/, function (next) {
      browser.get("/")
      expect(browser.getTitle()).to.eventually.contain("Z");
      next();
    });
};
```

output:
```
Feature: XY

  Scenario: I want X   # test/features/test.feature:2
    When I want X      # test/features/stepDefinitions.js:9

  Scenario: I want Y   # test/features/test.feature:4
    When I want Y      # test/features/stepDefinitions.js:15

Feature: Z

  Scenario: I want Z   # test/features/test2.feature:2
    When I want Z      # test/features/stepDefinitions.js:21

3 scenarios (3 passed)
3 steps (3 passed)
0m00.009s
AssertionError: expected 'A Title' to include 'X'
[launcher] Process exited with error code 1
```
My expectation was for all to be executed with inline errors - here is what happens if I execute via cucumber - I haven't setup selenium so it's just failing on 'ReferenceError: browser is not defined...', but it's reporting errors correctly for each scenario and it's summarising the errors at the end
```
Feature: XY

  Scenario: I want X   # test/features/test.feature:2
    When I want X      # test/features/stepDefinitions.js:9
      ReferenceError: browser is not defined...

  Scenario: I want Y   # test/features/test.feature:4
    When I want Y      # test/features/stepDefinitions.js:15
      ReferenceError: browser is not defined...

Feature: Z

  Scenario: I want Z   # test/features/test2.feature:2
    When I want Z      # test/features/stepDefinitions.js:21
      ReferenceError: browser is not defined...

Failing scenarios:
test/features/test.feature:2 # Scenario: I want X
test/features/test.feature:4 # Scenario: I want Y
test/features/test2.feature:2 # Scenario: I want Z

3 scenarios (3 failed)
3 steps (3 failed)
0m00.003s
```

**Comment by mattfritz** [comment]
It's hard to tell without the `browser` object, but I can replicate the issue. Since `chai-as-promised` returns a promise and does not throw an exception, the callback is not handling failure because it's not being notified.

Try using:

```js
expect(browser.getTitle()).to.eventually.contain("X").and.notify(next);
```
instead of:

```js
expect(browser.getTitle()).to.eventually.contain("X");
next();
```

and see if you get better results. If you are using vanilla chai on other steps (without `eventually`), it should throw an exception instead and fail the step.

Give that a shot and let me know what you find. I don't think this is a bug with the plugin since it is using a standard cucumber reporter, not the protractor reporter.

**Comment by bmsoko** [comment]
Hi @mattfritz I was having a problem with `protractor-cucumber-framework` for which I created an issue on protractor's github (https://github.com/cucumber/cucumber-js/issues/492) I had added what you suggested:

```javascript
   this.Then(/^I see that the slider has moved/, function (done) {
        browser.sleep(500);
        sliderWidgetPage.getImageAndAttribute(0,'data-url').then(function (attrVal) {
            expect(attrAtX1Time).to.eventually.equal(attrVal).and.not.notify(done);

        });
     done();
    });
```javascript


Although it closes the browser,  but no matter if I "force" the `expect` to fail, it always passes, so it does not works for me! what would you suggest?  please help!

**Comment by darrinholst** [comment]
that last `done()` is getting called immediately and not waiting for the  `getImageAndAttribute` nor the `browser.sleep` promises to complete. Your step is done at that point and everything in the `then` is ignored. There are several ways to do this. If you're using a current version of cucumber that knows about promises you can just return the promise...

```javascript
    this.Then(/^I see that the slider has moved/, function () {
        return browser.sleep(500).then(function () {
            return expect(sliderWidgetPage.getImageAndAttribute(0,'data-url')).to.eventually.equal('expectedValue');
        });
    });
```

if not you'll need to use the `done` callback

```javascript
    this.Then(/^I see that the slider has moved/, function (done) {
        browser.sleep(500).then(function () {
            expect(sliderWidgetPage.getImageAndAttribute(0,'data-url')).to.eventually.equal('expectedValue').and.notify(done);
        });
    });
```

Hope that helps

**Comment by bmsoko** [comment]
I had removed the `browser.sleep()` and I left it as this:

```javascript
   this.Then(/^I see that the slider has moved$/, function (done) {

        expect(sliderWidgetPage.getImageAndAttribute(0,'data-url'))
            .to.eventually.equal(attrAtX1Time).and.notify(done);
        });
```
And I got this error with both suggestion that you made:

```console
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
..F

(::) failed steps (::)

Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
```

What am I doing wrong?  I had followed also this example:
http://stuff.aftnn.org/acceptance-testing-cucumber.js-protractor/index.html#18

Thanks for your assistance!

**Comment by darrinholst** [comment]
Depends on which version you're using of the 2 you posted. If it's the first version then that tells me that `getImageAndAttribute` didn't resolve within 5 seconds. If you're using the second version where you're returning the promise then you need to remove the `done` parameter from the function signature as that tells cucumber to wait until it is called.

**Comment by ebacka** [comment]
https://github.com/nathanboktae/chai-dom/issues/33
