### ISSUE TITLE
Timeouts Not Working with Protractor Cucumber Framework

### ISSUE THREAD

**Issue by stevenmccord** [mattfritz/protractor-cucumber-framework#9]
I am utilizing a cucumber / protractor combination and I can't seem to increase the timeout for steps to run more than the 5000 milisecond limit.  

Here is an example of what I am running:

https://gist.github.com/stevenmccord/0997c2c5760540d4709b

Also, here are the versions of everything that I am running:

```bash
cucumberjs --version
0.9.2

protractor --version
Version 3.0.0
```

I have been chatting on the Glitter channel as well, but it doesn't appear anything has been able to be resolved, and the recommendation was to open an issue to see if there is a bug, or maybe there is a workaround.  

Thanks!

**Comment by mattfritz** [comment]
This shouldn't be part of the plugin, but what does your `protractor.conf` look like? Also, what is the specific error in your output?

**Comment by stevenmccord** [comment]
Thanks for the response, yeah I wasn't sure where this would lie actually, but here is the error that I receive and here is the conf.js.  Appreciate the help!

``` bash
      Error: Step timed out after 5000 milliseconds
          at Timer.listOnTimeout (timers.js:92:15)
```

https://gist.github.com/stevenmccord/5415b7eeb489ee16b71c

**Comment by mattfritz** [comment]
Thats strange, I saw that exact error [here](https://github.com/mattfritz/protractor-cucumber-framework/issues/4) and the solution was to update to cucumber `v0.9.2` (which it looks like you have gobally). Try deleting your `node_modules` to see if you might have an old version cached in the project and `npm install` again.

I'm going to close this for now since it's not related to the framework plugin. Let me know if you think otherwise or have additional info

**Comment by antda** [comment]
This is an cucumber step-timeout and the following code worked for us:
```javascript
module.exports = function() {
    this.setDefaultTimeout(60 * 1000);
}; 
```

**Comment by stevenmccord** [comment]
As a note, I have everything installed globally and it isn't working.  I actually looked back and notice in the documentation they say not to do that with the framework so I tried that, and it was the same result.  However, @antda timeout suggestion worked great for me, so although I think this is still a problem, I am good with that suggestion.  Thanks!

**Comment by Kureev** [comment]
@antda Where you write these lines?

**Comment by antda** [comment]
Hi!
Our acceptance-tests are located here:
https://github.com/sklintyg/webcert/tree/develop/test/acceptance
and the lines are located here:
https://github.com/sklintyg/webcert/blob/develop/test/acceptance/features/steps/env.js

**Comment by Kureev** [comment]
Thanks, @antda !

**Comment by dinvlad** [comment]
Is it still supposed to work with v2 and v3? Thanks

**Comment by darrinholst** [comment]
This framework doesn't do anything to define the cucumber timeout value so there should be nothing in any versions here that stop it from working.

**Comment by dinvlad** [comment]
Got it, I thought setDefaultTimeout() is a feature specific to this framework, but now I see it's part of Cucumber.js API.

Thanks again.
